services:
  app:
    build:
      context: .
    container_name: fastapi-test-task-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://fastapi_user:fastapi_password@db:5432/fastapi_service}
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: fastapi-test-task-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fastapi_service}
      POSTGRES_USER: ${POSTGRES_USER:-fastapi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastapi_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fastapi_user} -d ${POSTGRES_DB:-fastapi_service}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
